from . import account_payment_term
from . import res_partner
from . import project_units
from . import phase_units
from . import property_developer
from . import project_stock
from . import reservation
from . import sale_contract
from . import sale_installment
from . import developer_dashboard
