from . import account_payment_term
from . import res_partner
from . import project_units
from . import project_commercial
from . import phase_units
from . import phase_commercial
from . import property_developer
from . import unit_release
from . import unit_block
from . import property_sale_availability
from . import commercial_approval
from . import price_book
from . import price_rule
from . import property_pricing
from . import promotion
from . import payment_plan
from . import project_stock
from . import reservation
from . import reservation_v2
from . import sale_contract
from . import sale_contract_v2
from . import sale_installment
from . import sale_installment_v2
from . import contract_amendment
from . import contract_changes
from . import developer_dashboard
from . import developer_dashboard_v2
